### ISSUE TITLE
All calculations in the master map need to replace '.filled(0)' with '.fillna(0)'

### ISSUE THREAD

**Issue by greensh16** [ACCESS-Hive/ACCESS-MOPPeR#27]
'.filled(0)' doesn't work with Xarray.

**Comment by paolap** [comment]
I'll fix that now, I was nearly ready to merge :-)

**Comment by paolap** [comment]
I've done this, I'm merging paola_interp now

**Comment by paolap** [comment]
oops sorry I missed the master_map reference I changed that in cli_functions and calculations. Will fix this now

**Comment by paolap** [comment]
really done
